disabled_rules: # rule identifiers to exclude from running
    - force_cast
    - line_length
    - identifier_name
    - cyclomatic_complexity
    - nesting
    - class_delegate_protocol
    - for_where
    - function_body_length
    - control_statement
# Conflicts with Xcods default style
    - multiple_closures_with_trailing_closure

#  - function_body_length
#  - cyclomatic_complexity
#  - empty_enum_arguments
#  - trailing_whitespace
  
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
